version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniforge3-25.11"


conda:
  environment: docs/rtd_env.yml


sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
