"""Sequential Ray Tracing."""

from .lensdata import CoordBreak, LensData, SurfaceRow
from .launch import Field, Sampling, launch
from .spencer_and_murty import (
    DEFAULT_TOL_SAG,
    STATUS_CLIP,
    STATUS_MISS,
    STATUS_NEWTON,
    STATUS_OK,
    STATUS_TIR,
    STYPE_EVAL,
    STYPE_REFLECT,
    STYPE_REFRACT,
    SURFACE_INTERSECTION_DEFAULT_MAXITER,
    RayStatus,
    RayTraceResult,
    raytrace,
    refract,
    reflect,
)
from .surfaces import (
    Biconic,
    CallableShape,
    Chebyshev,
    Conic,
    EvenAsphere,
    Jacobi,
    OffAxisConic,
    Plane,
    Q2D,
    Shape,
    Sphere,
    Surface,
    Toroid,
    XY,
    Zernike,
    circular_aperture,
)
from .paraxial import (
    FirstOrderProperties,
    back_focal_length,
    effective_focal_length,
    entrance_pupil_z,
    first_order,
    front_focal_length,
    paraxial_image_distance,
    system_matrix,
)
from .analysis import (
    axial_color,
    distortion,
    field_curvature,
    lateral_color,
    wavefront,
    wavefront_zernike_fit,
    transverse_ray_aberration,
)
from .opt import (
    aim_rays,
    geometric_psf_histogram,
    locate_ep,
    locate_xp,
    opd_from_raytrace,
    rms_spot_radius,
    spot_centroid,
    xp_reference_sphere,
)

FRAUNHOFER_LINES_UM = {
    'C': 0.6562725,
    'd': 0.5875618,
    'F': 0.4861327,
}

__all__ = [
    'FRAUNHOFER_LINES_UM',
    'LensData',
    'SurfaceRow',
    'CoordBreak',
    'raytrace',
    'refract',
    'reflect',
    'Field',
    'Sampling',
    'launch',
    'aim_rays',
    'Surface',
    'Shape',
    'CallableShape',
    'Plane',
    'Sphere',
    'Conic',
    'OffAxisConic',
    'EvenAsphere',
    'Q2D',
    'Zernike',
    'XY',
    'Chebyshev',
    'Jacobi',
    'Toroid',
    'Biconic',
    'circular_aperture',
    'system_matrix',
    'paraxial_image_distance',
    'effective_focal_length',
    'entrance_pupil_z',
    'back_focal_length',
    'front_focal_length',
    'first_order',
    'FirstOrderProperties',
    'transverse_ray_aberration',
    'xp_reference_sphere',
    'opd_from_raytrace',
    'locate_ep',
    'locate_xp',
    'wavefront',
    'wavefront_zernike_fit',
    'distortion',
    'field_curvature',
    'axial_color',
    'lateral_color',
    'spot_centroid',
    'rms_spot_radius',
    'geometric_psf_histogram',
    'RayTraceResult',
    'RayStatus',
    'STYPE_REFLECT',
    'STYPE_REFRACT',
    'STYPE_EVAL',
    'STATUS_OK',
    'STATUS_NEWTON',
    'STATUS_CLIP',
    'STATUS_MISS',
    'STATUS_TIR',
    'DEFAULT_TOL_SAG',
    'SURFACE_INTERSECTION_DEFAULT_MAXITER',
]
