"""Sequential Ray Tracing.

This namespace re-exports the kernel, surfaces, paraxial, launch, and the core
analysis/opt entry points.  The heavier layers live in their submodules and are
imported from there: prysm.x.raytracing.aberrations (seidel_aberrations),
.design (Problem + operands), .tolerance (sensitivity_table, monte_carlo),
.raygen (ray generators), .plotting, and .io (Zemax / Code V readers).
"""

from .lensdata import CoordBreak, LensData, SurfaceRow
from .launch import Field, Sampling, launch
from .system import (
    ApertureSpec,
    FieldSet,
    OpticalSystem,
    System,
)
from .listings import (
    aperture_table,
    decenter_table,
    surface_table,
)
from .spencer_and_murty import (
    DEFAULT_TOL_SAG,
    STATUS_CLIP,
    STATUS_MISS,
    STATUS_NEWTON,
    STATUS_OK,
    STATUS_TIR,
    STYPE_EVAL,
    STYPE_REFLECT,
    STYPE_REFRACT,
    SURFACE_INTERSECTION_DEFAULT_MAXITER,
    RayStatus,
    RayTraceResult,
    decode_status,
    raytrace,
    refract,
    reflect,
)
from .surfaces import (
    Biconic,
    CallableShape,
    Chebyshev,
    Conic,
    EvenAsphere,
    Jacobi,
    OffAxisConic,
    Plane,
    Q2D,
    Shape,
    Sphere,
    Surface,
    Toroid,
    XY,
    Zernike,
    annular_aperture,
    circular_aperture,
)
from .paraxial import (
    FirstOrderProperties,
    back_focal_length,
    effective_focal_length,
    entrance_pupil_z,
    first_order,
    front_focal_length,
    paraxial_image_distance,
    system_matrix,
)
from .analysis import (
    axial_color,
    chromatic_focal_shift,
    distortion,
    field_curvature,
    lateral_color,
    wavefront,
    wavefront_zernike_fit,
    transverse_ray_aberration,
    ray_aberration_fans,
    opd_fans,
    spot_diagrams,
    spot_rms_radius,
    spot_geometric_radius,
    DistortionResult,
    FieldCurvatureResult,
    RayFanGrid,
    OPDFanGrid,
    SpotGrid,
)
from .opt import (
    aim_rays,
    geometric_psf_histogram,
    locate_ep,
    locate_xp,
    rms_spot_radius,
    spot_centroid,
    xp_reference_sphere,
)
from .field import (
    FieldTraceResult,
    PRTResult,
    PupilField,
    amplitude_apodization,
    interface_coefficients,
    pupil_field,
    pupil_field_psf,
    pupil_field_to_wavefront,
    raytrace_field,
    raytrace_prt,
    reference_sphere_coords,
    surface_normals_from_trace,
    unpolarized_amplitude,
)

FRAUNHOFER_LINES_UM = {
    'C': 0.6562725,
    'd': 0.5875618,
    'F': 0.4861327,
}

__all__ = [
    'FRAUNHOFER_LINES_UM',
    'LensData',
    'SurfaceRow',
    'CoordBreak',
    'OpticalSystem',
    'System',
    'ApertureSpec',
    'FieldSet',
    'surface_table',
    'aperture_table',
    'decenter_table',
    'raytrace',
    'refract',
    'reflect',
    'Field',
    'Sampling',
    'launch',
    'aim_rays',
    'Surface',
    'Shape',
    'CallableShape',
    'Plane',
    'Sphere',
    'Conic',
    'OffAxisConic',
    'EvenAsphere',
    'Q2D',
    'Zernike',
    'XY',
    'Chebyshev',
    'Jacobi',
    'Toroid',
    'Biconic',
    'circular_aperture',
    'annular_aperture',
    'system_matrix',
    'paraxial_image_distance',
    'effective_focal_length',
    'entrance_pupil_z',
    'back_focal_length',
    'front_focal_length',
    'first_order',
    'FirstOrderProperties',
    'transverse_ray_aberration',
    'xp_reference_sphere',
    'locate_ep',
    'locate_xp',
    'wavefront',
    'wavefront_zernike_fit',
    'distortion',
    'field_curvature',
    'axial_color',
    'chromatic_focal_shift',
    'lateral_color',
    'ray_aberration_fans',
    'opd_fans',
    'spot_diagrams',
    'spot_rms_radius',
    'spot_geometric_radius',
    'DistortionResult',
    'FieldCurvatureResult',
    'RayFanGrid',
    'OPDFanGrid',
    'SpotGrid',
    'spot_centroid',
    'rms_spot_radius',
    'geometric_psf_histogram',
    'pupil_field',
    'pupil_field_to_wavefront',
    'pupil_field_psf',
    'raytrace_field',
    'raytrace_prt',
    'PupilField',
    'FieldTraceResult',
    'PRTResult',
    'amplitude_apodization',
    'reference_sphere_coords',
    'interface_coefficients',
    'surface_normals_from_trace',
    'unpolarized_amplitude',
    'RayTraceResult',
    'RayStatus',
    'decode_status',
    'STYPE_REFLECT',
    'STYPE_REFRACT',
    'STYPE_EVAL',
    'STATUS_OK',
    'STATUS_NEWTON',
    'STATUS_CLIP',
    'STATUS_MISS',
    'STATUS_TIR',
    'DEFAULT_TOL_SAG',
    'SURFACE_INTERSECTION_DEFAULT_MAXITER',
]
