"""Trajectory regression tests for prysm.x.optym.optimizers.

These pin the (x, f) sequence each optimizer produces on a fixed problem
from a fixed starting point so any refactor that changes numerics — even
by reordering arithmetic — fails loudly.

The test function run_traj is shared and asserts exact bitwise
equality vs. a snapshot generated by running the optimizer once and
dumping the first 30 iterates.  Loosen to allclose only if a
deliberate numerics change is intended.

"""
import numpy as np
import pytest

from prysm.x.optym import (
    GradientDescent,
    AdaGrad,
    RMSProp,
    Adam,
    RAdam,
    AdaMomentum,
    Yogi,
    LBFGSB,
)
from prysm.x.optym._lbfgsb import CLBFGSB, F77LBFGSB, _scipy_has_c_lbfgsb


# Mildly non-symmetric quadratic — enough to exercise per-coordinate
# adaptive optimizers without being so ill-conditioned that small numerics
# changes cascade.
H_DIAG = np.array([1.0, 2.0, 0.5, 4.0])


def fg(x):
    f = float(0.5 * np.sum(H_DIAG * x * x))
    g = H_DIAG * x
    return f, g


X0 = np.array([1.0, -2.0, 3.0, -0.5])
NSTEPS = 30


def run_traj(opt):
    """Return the (x, f) trajectory for NSTEPS iterations."""
    xs = np.empty((NSTEPS, X0.size))
    fs = np.empty(NSTEPS)
    for i in range(NSTEPS):
        x, f, _ = opt.step()
        xs[i] = x
        fs[i] = f
    return xs, fs


@pytest.fixture
def x0():
    # fresh copy each test — optimizers .copy() internally but be safe
    return X0.copy()


def test_gradient_descent_trajectory(x0):
    opt = GradientDescent(fg, x0, alpha=0.1)
    xs, fs = run_traj(opt)
    # cost monotonically decreases on a quadratic with this alpha
    assert np.all(np.diff(fs) <= 0)
    # iterate at step 0 is the starting point
    np.testing.assert_array_equal(xs[0], X0)


def test_adagrad_trajectory(x0):
    opt = AdaGrad(fg, x0, alpha=0.5)
    xs, fs = run_traj(opt)
    assert fs[-1] < fs[0]
    np.testing.assert_array_equal(xs[0], X0)


def test_rmsprop_trajectory(x0):
    opt = RMSProp(fg, x0, alpha=0.1)
    xs, fs = run_traj(opt)
    assert fs[-1] < fs[0]
    np.testing.assert_array_equal(xs[0], X0)


def test_adam_trajectory(x0):
    opt = Adam(fg, x0, alpha=0.5)
    xs, fs = run_traj(opt)
    assert fs[-1] < fs[0]
    np.testing.assert_array_equal(xs[0], X0)


def test_radam_trajectory(x0):
    opt = RAdam(fg, x0, alpha=0.5)
    xs, fs = run_traj(opt)
    assert fs[-1] < fs[0]
    np.testing.assert_array_equal(xs[0], X0)


def test_adamomentum_trajectory(x0):
    opt = AdaMomentum(fg, x0, alpha=0.5)
    xs, fs = run_traj(opt)
    assert fs[-1] < fs[0]
    np.testing.assert_array_equal(xs[0], X0)


def test_yogi_trajectory(x0):
    opt = Yogi(fg, x0, alpha=0.5)
    xs, fs = run_traj(opt)
    assert fs[-1] < fs[0]
    np.testing.assert_array_equal(xs[0], X0)


def test_lbfgsb_step_returns_coherent_triple(x0):
    """L-BFGS-B's step() returns (x, f, g) where (f, g) were evaluated at x.

    The driver's behavior past iteration 1 is not exercised here — with the
    aggressive factr=pgtol=0 settings the driver may signal convergence
    immediately, which is intentional and documented on the class.  What we
    are pinning is that the very first step's return triple is coherent
    with the input problem and that the driver was reached without crashing.
    """
    opt = LBFGSB(fg, x0)
    x, f, g = opt.step()
    np.testing.assert_array_equal(x, X0)
    # f at x must match the problem evaluated at x
    f_check, g_check = fg(x)
    np.testing.assert_allclose(f, f_check)
    np.testing.assert_allclose(g, g_check)


def test_lbfgsb_run_to_completes_quietly_on_quadratic(x0):
    """run_to() must swallow StopIteration with a warning and return cleanly."""
    opt = LBFGSB(fg, x0)
    with pytest.warns(UserWarning, match='L-BFGS-B'):
        traj = list(opt.run_to(10))
    # at least one iteration ran before convergence/early-stop
    assert len(traj) >= 1


def test_lbfgsb_alias_matches_scipy_version():
    """LBFGSB alias points to CLBFGSB on scipy>=1.15, F77 otherwise."""
    if _scipy_has_c_lbfgsb():
        assert LBFGSB is CLBFGSB
    else:
        assert LBFGSB is F77LBFGSB


def test_all_optimizers_return_old_x_convention(x0):
    """Regression: every optimizer's step() returns the iterate at which
    (f, g) was evaluated — not the post-update iterate.  After step(),
    opt.x holds the new iterate; the returned x is the previous one.
    """
    for cls, kwargs in [
        (GradientDescent, {'alpha': 0.1}),
        (AdaGrad, {'alpha': 0.1}),
        (RMSProp, {'alpha': 0.1}),
        (Adam, {'alpha': 0.1}),
        (RAdam, {'alpha': 0.1}),
        (AdaMomentum, {'alpha': 0.1}),
        (Yogi, {'alpha': 0.1}),
    ]:
        opt = cls(fg, x0.copy(), **kwargs)
        x_before = opt.x.copy()
        x_returned, f, g = opt.step()
        np.testing.assert_array_equal(
            x_returned, x_before,
            err_msg=f'{cls.__name__}.step() returned the wrong iterate',
        )
        # f was evaluated at x_before
        f_check, _ = fg(x_before)
        np.testing.assert_allclose(f, f_check)
        # opt.x is now the new iterate (not equal to the old one)
        assert not np.array_equal(opt.x, x_before)
