name: prysm-ci
channels:
  - conda-forge
dependencies:
  - python=3.14
  - pip
  - hatchling
  - numpy
  - scipy
  - matplotlib
  - scikit-image
  - imageio
  - pandas
  - h5py
  - pyyaml
  - pytest
  - pytest-cov
  - coverage
  - coveralls
  - pip:
      - refractiveindex
